### ISSUE TITLE
Glove-seed.txt file

### ISSUE THREAD

**Issue by Trinadhbabu** [abdulfatir/twitter-sentiment-analysis#11]
where can we get Glove-seed.txt file.

**Comment by yrluo** [comment]
Glove-seeds can be downloaded here:
http://nlp.stanford.edu/data/glove.twitter.27B.zip
You should use the 200 dimentional txt file.

**Comment by tyramisoux** [comment]
the glove.txt (I tried the 100d and 200d) contains strange unicode characters at several positions. In fact this seems to be Japanese and Russian Text in UTF8 which means - after translation, phrases like "thanks for following me" (In Japanese) or "its free" in Russian :-)
The runs in an "UnicodeDecodeError: 'charmap' codec can't decode byte ...."-Error.

How did you handle it? Guess I simply will clear the file by stripping everything above 0x7f

The Error occurs within an "enumerate" so no chance simply using "try".
