### ISSUE TITLE
No needed files of FREQ_DIST_FILE

### ISSUE THREAD

**Issue by tobegit3hub** [abdulfatir/twitter-sentiment-analysis#3]
How can we find the `FREQ_DIST_FILE` for training the models?

Refer to https://github.com/abdulfatir/twitter-sentiment-analysis/blob/master/extract-cnn-feats.py#L9 .

```
FREQ_DIST_FILE = '../train-processed-freqdist.pkl'
```

Can you upload these necessary files so that everyone can train the models easily?

**Comment by abdulfatir** [comment]
Please see usage in [Readme](https://github.com/abdulfatir/twitter-sentiment-analysis/blob/master/README.md). You need to generate `FREQ_DIST_FILE` for your own dataset.
