### ISSUE TITLE
Some Questions 

### ISSUE THREAD

**Issue by I-am-coder** [abdulfatir/twitter-sentiment-analysis#4]
Can you please give the link of the dataset used?
Also, don't yot think that apart from positive and negative sentiment label, neutral label should also be applied to sentiment classification problem?

**Comment by roshangm1** [comment]
Train Set can be found in other branch 'svm'. I don't know about the test set though,

**Comment by abdulfatir** [comment]
@I-am-coder The dataset was private for a Kaggle in-class contest. You can search for other publically available datasets. The contest was a binary classification problem. I just pushed my code for the contest. This is in no way SOTA or current research in sentiment analysis.
@roshangm1 That is just a sample of dataset, not the entire dataset.

**Comment by roshangm1** [comment]
okay @abdulfatir Thank You!!

**Comment by I-am-coder** [comment]
thanks
