### ISSUE TITLE
No module found error. Can you please tell the steps to be followed.

### ISSUE THREAD

**Issue by kinnu183** [abdulfatir/twitter-sentiment-analysis#5]
![error](https://user-images.githubusercontent.com/24778890/36091870-50d36314-100b-11e8-8a42-2fc51eb5a158.JPG)

**Comment by abdulfatir** [comment]
You need to install `nltk`.

**Comment by kinnu183** [comment]
I'm using python 2.7 in 64-bit version. They are suggesting to use a 32-bit version to download and use nltk. Is there any other way?
