### ISSUE TITLE
problem in first step

### ISSUE THREAD

**Issue by dhananjayfarmah** [abdulfatir/twitter-sentiment-analysis#7]
i am just a beginner so sorry if i am asking a very basic question..
i have my training and test data sets saved in csv format....in your first step it says run preprocess.py on training and test dataset...how to do that? does that mean i have to specify the path of csv files somewhere within the code(preprocess.py)? because i am not able to find that,,please help..thank you:))

**Comment by abdulfatir** [comment]
It is clearly written in the Readme. Run as `python preprocess.py <csv_file_name>`.
