### ISSUE TITLE
seeds file and arabic sentiment analysis

### ISSUE THREAD

**Issue by adelabdelli** [abdulfatir/twitter-sentiment-analysis#8]
Hello, i'm working on Arabic sentiment analysis, and i'm wondering if these codes will work for me ? and i'm looking from where you got seeds file ? and how can i make one ?
and from where you get this files : 
```
FREQ_DIST_FILE = '../train-processed-freqdist.pkl'
BI_FREQ_DIST_FILE = '../train-processed-freqdist-bi.pkl'
TRAIN_PROCESSED_FILE = '../train-processed.csv'
TEST_PROCESSED_FILE = '../test-processed.csv'
GLOVE_FILE = './dataset/glove-seeds.txt'
```

**Comment by abdulfatir** [comment]
It should work for any language in theory. However, as far as I know, Arabic doesn't have word boundaries as good as English so I cannot really say how much you need to change. Seeds are the glove word vectors available from StanfordNLP group's website. If you want to generate for Arabic, you'll have to use Word2Vec or Glove on a huge dataset of Arabic tweets. 

For all the other files, please read the Readme file.
